##======================================================================================================================
##  SAMPLE - @brief@
##  Copyright : SAMPLE Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SAMPLE Integration Tests
on:
  push:
    branches:
      - main

concurrency:
  group: sample-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    uses: jfalcou/copacabana/.github/workflows/integration.yml@643b9f4cac5bbfa7a6cfe6da385478c5aa3773f8 # v6
    with:
      project: sample
      cxx-compiler: clang++
      cxx-flags: -std=c++20
