##======================================================================================================================
##  SAMPLE - @brief@
##  Copyright : SAMPLE Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SAMPLE Windows Tests
on:
  workflow_call:

jobs:
  windows:
    name: ${{ matrix.compiler.name }} (${{ matrix.options }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { name: "msvc"    , preset: "msvc"    }
          - { name: "clang-cl", preset: "clangcl" }

        options: [Debug, Release]

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v7

      - name: Configure CMake and Build
        uses: jfalcou/copacabana/.github/actions/config@643b9f4cac5bbfa7a6cfe6da385478c5aa3773f8 # v6
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}

      - name: Run Unit Tests
        uses: jfalcou/copacabana/.github/actions/test@643b9f4cac5bbfa7a6cfe6da385478c5aa3773f8 # v6
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}
