##==================================================================================================
##  Copacabana - Common CMake Package Tools
##  Copyright : Copacabana Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##==================================================================================================
name: Copacabana - Mac OS X Unit Tests
on:
  workflow_call:

jobs:

  macosx:
    runs-on: [macos-14]
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { compiler: clang++     , mode: dev-normal }
        - { compiler: clang++     , mode: dev-asan   }
        - { compiler: clang++     , mode: dev-tsan   }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v6.0.2
      - name: Running Test with ${{ matrix.cfg.compiler }} in ${{ matrix.cfg.mode }} mode
        run: |
          cd example
          cmake --preset=${{ matrix.cfg.mode }} -DCMAKE_CXX_COMPILER=${{ matrix.cfg.compiler }}         \
                -DCPM_COPACABANA_SOURCE=$GITHUB_WORKSPACE -DCMAKE_CXX_FLAGS="${{ matrix.cfg.option }}"
          cmake --build --preset=${{ matrix.cfg.mode }} --target example-test --parallel 2
          ctest --preset=${{ matrix.cfg.mode }} --output-on-failure
