##==================================================================================================
##  Copacabana - Common CMake Package Tools
##  Copyright : Copacabana Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##==================================================================================================
name: Unit Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    name: Linux
    uses: ./.github/workflows/linux.yml

  macosx:
    name: Mac OS X
    uses: ./.github/workflows/macos.yml

  windows:
    name: Windows
    uses: ./.github/workflows/windows.yml
